- build.gradle
- checkstyle/naver-checkstyle-rules.xml
- checkstyle/naver-checkstyle-suppressions.xml
<br>
- sonarcloud와 github action, checkstyle, jacoco활용 CI
- checkstyle : 정적 코드 분석(naver convention)
- jacoco : 테스트 커버리지 분석후 sonarcloud 통해 커버리지 범위 통과 한 경우에만 병합 허용
<br>
- checkstyle 관련 sourceSets 설정 : CompileQuerydsl 관련 이슈를 잡는다고 해서 설정해두었으나 추후Querydsl 관련 이슈 발생 가능성 있음
- jacoco 관련 테스트 코드 통과가 정말 어려운 상황 발생시 jacocoTestReport에 property를 설정함으로써 예외적용 가능
<br>
> [Feat] ci ver1 적용(린트, 테스트 자동화)

- .githubci_v1.yml
<br>
- ci ver1 적용관련 yml추가
<br>
- ci ver1 적용관련 yml추가합니다
<br>
> [PS-28]feat: ci ver1 적용_yml추가

- src/docs/asciidoc/api/auth/login.adoc
- src/docs/asciidoc/api/auth/reissue.adoc
- src/main/java/com/tf4/photospot/auth/application/AuthService.java
- src/main/java/com/tf4/photospot/auth/application/JwtService.java
- src/main/java/com/tf4/photospot/auth/application/response/ReissueTokenResponse.java
- src/main/java/com/tf4/photospot/auth/domain/JwtRepository.java
- src/main/java/com/tf4/photospot/auth/presentation/AuthController.java
- src/main/java/com/tf4/photospot/auth/presentation/request/ReissueRequest.java
- src/main/java/com/tf4/photospot/auth/util/JwtProvider.java
- src/main/java/com/tf4/photospot/global/config/jwt/JwtProperties.java
- src/main/java/com/tf4/photospot/global/exception/domain/AuthErrorCode.java
- src/main/java/com/tf4/photospot/user/application/UserService.java
- src/test/java/com/tf4/photospot/auth/application/AuthServiceTest.java
- src/test/java/com/tf4/photospot/auth/application/JwtServiceTest.java
- src/test/java/com/tf4/photospot/spring/docs/auth/AuthControllerDocsTest.java
- src/test/java/com/tf4/photospot/user/application/UserServiceTest.java
<br>
- 토큰 유효성 검증 및 액세스 토큰 재발급 기능 구현
- 토큰 관련 예외 처리 구현
- 테스트 코드 작성
<br>
user 관련 예외 처리는 PR을 분리해서 올리는 게 깔끔할 것 같아서 user 관련 기능 구현할 때 추가하겠습니다.
(질문) 예외 케이스에 대한 API Docs도 작성해야 하나요?
<br>
> [Feat] JWT 유효성 검증 및 액세스 토큰 재발급 구현

- src/test/java/com/tf4/photospot/IntegrationTestSupport.java
- src/test/java/com/tf4/photospot/auth/application/AuthServiceTest.java
- src/test/java/com/tf4/photospot/auth/application/JwtServiceTest.java
- src/test/java/com/tf4/photospot/spot/application/SpotServiceTest.java
- src/test/java/com/tf4/photospot/user/application/UserServiceTest.java
<br>
- 통합테스트코드에서 `@Sql` 어노테이션을 삭제하고 `@Transactional` 어노테이션을 추가했습니다.
<br>
- 추가 수정사항 있으면 말씀해주세요.
<br>
> [Refactor] 테스트코드 수정

- .github/workflows/ci_v1.yml
- build.gradle
- settings.gradle
- src/main/java/com/tf4/photospot/post/application/request/PostUploadRequest.java
- src/main/resources/application.yml
- src/test/resources/application.yml
<br>
- CI_v1 : github repo SECRET TO env 설정 추가
- application.yml : KEY SETTING 관련 Properties -> default 프로필로 이동
<br>
-
<br>
> [FIX] ci_v1, application.yml 수정

- build.gradle
<br>
- jacoco test 리포트 파일 양식 변경
<br>
-
<br>
> [PS-38] fix: jacocoTestReport format change

- README.md
- src/docs/asciidoc/api/auth/auth.adoc
- src/docs/asciidoc/api/common/common.adoc
- src/docs/asciidoc/api/map/map.adoc
- src/docs/asciidoc/api/spot/spot.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/com/tf4/photospot/global/argument/CoordinateValidator.java
- src/main/resources/static/docs/index.html
- src/test/java/com/tf4/photospot/spring/docs/CustomResponseFieldsSnippet.java
- src/test/java/com/tf4/photospot/spring/docs/RestDocsSupport.java
- src/test/java/com/tf4/photospot/spring/docs/auth/AuthControllerDocsTest.java
- src/test/java/com/tf4/photospot/spring/docs/common/CommonController.java
- src/test/java/com/tf4/photospot/spring/docs/common/CommonDocsTest.java
- src/test/java/com/tf4/photospot/spring/docs/common/ErrorCodeResponse.java
- src/test/java/com/tf4/photospot/spring/docs/map/MapControllerDocsTest.java
- src/test/java/com/tf4/photospot/spring/docs/spot/SpotControllerDocsTest.java
- src/test/resources/org/springframework/restdocs/templates/asciidoctor/errorcode-response-fields.snippet
- src/test/resources/org/springframework/restdocs/templates/asciidoctor/query-parameters.snippet
- src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
- src/test/resources/org/springframework/restdocs/templates/asciidoctor/response-fields.snippet
<br>
- document 공통 부분 template으로 생성
- column(optional, defaultValue, constaraints) 추가
- success, error example, error code 문서 추가
- readme에 docs api 문서 링크
<br>
- document에서 asciidoc 생성 경로를 class-name/method-name으로 자동 생성 되도록하고 공통 부분을 template으로 만들었습니다.
- RestDocsSupport에서 defaultValue, constraints 생성 등의 util 메서드를 추가했습니다.
[참고 링크]
- https://backtony.github.io/spring/2021-10-15-spring-test-3/#%EB%AC%B8%EC%84%9C-%EC%BB%A4%EC%8A%A4%ED%85%80%ED%95%98%EA%B8%B0
- https://techblog.woowahan.com/2597/
- https://browngoo.tistory.com/42
- https://0soo.tistory.com/210
> [Feat] Spring Rest Docs 공통 문서 추가, 리펙토링

- .github/workflows/ci-cd.yml
- .github/workflows/code-analysis.yml
- .gitignore
- Dockerfile
- appspec.yml
- build.gradle
- docker-compose.yml
- src/main/resources/application.yml
- src/test/resources/application.yml
<br>
- Github에서 secret 값으로 관리를 하면 배포를 할때 EC2 내에 값이 하드 코딩 되어서 AWS Parameter Store로 환경 변수를 관리하도록 했습니다.
- gitactions에서 AWS Key 기반 인증 대신 Role 임시 자격을 받아서 하도록 했습니다.
- ssh로 직접 EC2 내에 접속해서 배포하는 방식은 보안면에서 권장 되지 않고 확장성도 떨어져서 S3, CodeDeploy로 배포했습니다.
<br>
**[참고]**
**AWS Parameter store**
- https://kim-jong-hyun.tistory.com/120
- https://velog.io/@as9587/spring-boot-3.2%EC%97%90%EC%84%9C-aws-parameter-store-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0
**ECR & S3 & CodeDeploy 배포**
- https://velog.io/@kshired/Github-Actions-ECR-Auto-Scaling-Group-EC2-CodeDeploy-S3-를-사용하여-BlueGreen-CICD-구축하기#appspecyml-생성
- https://hoon9901.github.io/aws-codedeploy/
Role & OIDC
- https://zerone-code.tistory.com/11
- https://hudi.blog/open-id/
> [PS-66] CICD 배포 추가

- build.gradle
- lombok.config
- src/docs/asciidoc/api/spot/spot.adoc
- src/main/java/com/tf4/photospot/global/config/security/SecurityConfig.java
- src/main/java/com/tf4/photospot/global/exception/GlobalExceptionHandler.java
- src/main/java/com/tf4/photospot/spot/application/SpotService.java
- src/main/java/com/tf4/photospot/spot/application/response/SpotCoordResponse.java
- src/main/java/com/tf4/photospot/spot/infrastructure/SpotQueryRepository.java
- src/main/java/com/tf4/photospot/spot/presentation/SpotController.java
- src/main/java/com/tf4/photospot/spot/presentation/response/UserSpotHttpResponse.java
- src/main/java/com/tf4/photospot/spot/presentation/response/UserSpotListHttpResponse.java
- src/main/resources/application.yml
- src/main/resources/static/docs/index.html
- src/test/java/com/tf4/photospot/auth/presentation/AuthControllerTest.java
- src/test/java/com/tf4/photospot/spot/application/SpotServiceTest.java
- src/test/java/com/tf4/photospot/spring/docs/spot/SpotControllerDocsTest.java
<br>
- 자신이 작성한 방명록의 장소 목록 API
- exception handler error log 추가
- security ignore 경로 수정
<br>
<br>
> [FEAT] 자신이 작성한 방명록의 장소 목록 API

- src/main/java/com/tf4/photospot/global/config/security/SecurityConfig.java
- src/main/resources/static/docs/index.html
<br>
- ignore()의 StaticResourceLocation에 docs/index.html이 포함이 안 돼서 추가했습니다.
<br>
> [FIX] Rest Docs 접근 허용

- src/main/java/com/tf4/photospot/spot/application/SpotService.java
- src/main/java/com/tf4/photospot/spot/application/response/NearbySpotResponse.java
- src/main/java/com/tf4/photospot/spot/domain/SpotRepository.java
- src/main/java/com/tf4/photospot/spot/infrastructure/SpotQueryRepository.java
<br>
- 초기에 작성한 주변 스팟 조회 sql이 작성한 추천 스팟 조회와 중복되는 부분이 있어서 하나로 통합했습니다.
<br>
> [Refactor/PS-75] 주변 스팟 조회

- src/main/java/com/tf4/photospot/auth/presentation/request/LoginDto.java
- src/main/java/com/tf4/photospot/global/exception/domain/AuthErrorCode.java
- src/main/java/com/tf4/photospot/global/filter/CustomAuthenticationFilter.java
- src/test/java/com/tf4/photospot/auth/domain/OauthAttributesTest.java
- src/test/java/com/tf4/photospot/auth/presentation/AuthControllerTest.java
<br>
- 로그인 요청 시 필요한 값을 파라미터 -> body로 받도록 수정
<br>
> [fix] 로그인 요청 값 수정

- src/main/resources/application.yml
> [Fix] redis port 수정

- src/docs/asciidoc/index.adoc
- src/main/resources/static/docs/index.html
- src/test/resources/application.yml
<br>
- photo api restDocs 반영
<br>
- restdocs 파일 누락분 추가했습니다.
<br>
> [Docs] photo api restDocs 반영

- src/main/java/com/tf4/photospot/album/infrastructure/AlbumJdbcRepository.java
- src/test/java/com/tf4/photospot/album/application/AlbumServiceTest.java
<br>
- 앨범 목록 조회 시 앨범이 없으면 빈 리스트 반환
<br>
<br>
> [Fix] 앨범 목록 조회

- src/docs/asciidoc/api/bookmark/bookmark.adoc
- src/main/java/com/tf4/photospot/bookmark/application/BookmarkService.java
- src/main/java/com/tf4/photospot/bookmark/application/request/CreateBookmark.java
- src/main/java/com/tf4/photospot/bookmark/domain/Bookmark.java
- src/main/java/com/tf4/photospot/bookmark/domain/BookmarkFolder.java
- src/main/java/com/tf4/photospot/bookmark/presentation/BookmarkController.java
- src/main/java/com/tf4/photospot/bookmark/presentation/request/AddBookmarkHttpRequest.java
- src/main/java/com/tf4/photospot/bookmark/presentation/response/AddBookmarkHttpResponse.java
- src/main/java/com/tf4/photospot/global/exception/domain/BookmarkErrorCode.java
- src/main/java/com/tf4/photospot/spot/application/SpotService.java
- src/main/java/com/tf4/photospot/user/application/request/LoginUserInfo.java
- src/main/java/com/tf4/photospot/user/domain/User.java
- src/test/java/com/tf4/photospot/auth/application/JwtServiceTest.java
- src/test/java/com/tf4/photospot/bookmark/application/BookmarkServiceTest.java
- src/test/java/com/tf4/photospot/bookmark/domain/BookmarkFolderTest.java
- src/test/java/com/tf4/photospot/bookmark/presentation/request/AddBookmarkHttpRequestTest.java
- src/test/java/com/tf4/photospot/spring/docs/bookmark/BookmarkControllerDocsTest.java
- src/test/java/com/tf4/photospot/support/TestFixture.java
- src/test/java/com/tf4/photospot/user/application/UserServiceTest.java
<br>
- 북마크 추가 기능
- 북마크 폴더에 추가할 수 있는 북마크 개수는 별도의 칼럼 대신 애플리케이션에서 체크하도록 했습니다
<br>
PR #59 먼저 부탁드립니다
<br>
> [Feat] 북마크 추가

- src/docs/asciidoc/api/bookmark/bookmark.adoc
- src/main/java/com/tf4/photospot/bookmark/application/BookmarkService.java
- src/main/java/com/tf4/photospot/bookmark/application/request/CreateBookmark.java
- src/main/java/com/tf4/photospot/bookmark/application/response/BookmarkListResponse.java
- src/main/java/com/tf4/photospot/bookmark/application/response/BookmarkResponse.java
- src/main/java/com/tf4/photospot/bookmark/domain/Bookmark.java
- src/main/java/com/tf4/photospot/bookmark/infrastructure/BookmarkQueryRepository.java
- src/main/java/com/tf4/photospot/bookmark/presentation/BookmarkController.java
- src/main/java/com/tf4/photospot/bookmark/presentation/request/ReadBookmarkRequest.java
- src/main/java/com/tf4/photospot/post/infrastructure/PostJdbcRepository.java
- src/main/java/com/tf4/photospot/spot/application/SpotService.java
- src/test/java/com/tf4/photospot/bookmark/application/BookmarkServiceTest.java
- src/test/java/com/tf4/photospot/spot/application/SpotServiceTest.java
- src/test/java/com/tf4/photospot/spring/docs/bookmark/BookmarkControllerDocsTest.java
- src/test/java/com/tf4/photospot/spring/docs/spot/SpotControllerDocsTest.java
- src/test/java/com/tf4/photospot/support/TestFixture.java
<br>
- 북마크 폴더의 북마크 리스트 조회
- 북마크 스팟의 최신 방명록 사진을 같이 조회합니다
- 기존 추천 스팟 조회 API에서 사용하던 최신 방명록 조회 기능을 활용하도록 리펙토링 했습니다.
<br>
PR #60 먼저 부탁드립니다
<br>
> [Feat] 북마크 폴더의 북마크 리스트 조회

- src/docs/asciidoc/api/bookmark/bookmark.adoc
- src/main/java/com/tf4/photospot/bookmark/application/BookmarkService.java
- src/main/java/com/tf4/photospot/bookmark/application/request/ReadBookmarkFolderList.java
- src/main/java/com/tf4/photospot/bookmark/application/response/BookmarkFolderResponse.java
- src/main/java/com/tf4/photospot/bookmark/infrastructure/BookmarkQueryRepository.java
- src/main/java/com/tf4/photospot/bookmark/presentation/BookmarkController.java
- src/main/java/com/tf4/photospot/bookmark/presentation/response/BookmarkFolderListHttpResponse.java
- src/test/java/com/tf4/photospot/bookmark/application/BookmarkServiceTest.java
- src/test/java/com/tf4/photospot/spring/docs/bookmark/BookmarkControllerDocsTest.java
<br>
- 북마크 폴더 리스트 조회 기능
<br>
- PR #63 먼저 부탁드립니다
<br>
> [Feat] 북마크 폴더 리스트 조회

- src/docs/asciidoc/api/bookmark/bookmark.adoc
- src/main/java/com/tf4/photospot/bookmark/application/BookmarkService.java
- src/main/java/com/tf4/photospot/bookmark/domain/BookmarkFolder.java
- src/main/java/com/tf4/photospot/bookmark/infrastructure/BookmarkQueryRepository.java
- src/main/java/com/tf4/photospot/bookmark/presentation/BookmarkController.java
- src/main/java/com/tf4/photospot/bookmark/presentation/request/RemoveBookmarkHttpRequest.java
- src/main/java/com/tf4/photospot/global/exception/domain/BookmarkErrorCode.java
- src/test/java/com/tf4/photospot/bookmark/application/BookmarkServiceTest.java
- src/test/java/com/tf4/photospot/bookmark/domain/BookmarkFolderTest.java
- src/test/java/com/tf4/photospot/spring/docs/bookmark/BookmarkControllerDocsTest.java
<br>
- 북마크 삭제 기능 추가
- 북마크 폴더 삭제 기능 추가
- 북마크 폴더 삭제시 북마크도 같이 삭제됩니다.
<br>
- PR #63 먼저 부탁드립니다
<br>
> [Feat] 북마크, 북마크 폴더 삭제

- src/main/resources/static/docs/index.html
- rest docs 문서 충돌로 수정하고 제거하겠습니다.
<br>
> [docs] index.html 수정

- src/main/java/com/tf4/photospot/post/application/request/PostSearchType.java
- src/main/java/com/tf4/photospot/post/presentation/PostController.java
- src/test/java/com/tf4/photospot/post/application/request/PostSearchConditionTest.java
<br>
- 신고 게시글 필터링 기능이 추가되면서 방명록 미리보기 조회 시 userId를 받도록 변경했습니다.
<br>
<br>
> [fix] 스팟 방명록 미리보기 조회 조건 수정

- src/main/java/com/tf4/photospot/photo/presentation/PhotoController.java
- src/test/java/com/tf4/photospot/post/application/PostServiceTest.java
<br>
GlobalExceptionHandler : Required part 'file' is not present. fix
> [Fix] 사진 업로드 에러 발생 수정

- src/main/java/com/tf4/photospot/photo/application/S3Uploader.java
> [fix] 사진 파일 검증 수정

- src/main/java/com/tf4/photospot/post/application/PostService.java
- src/main/java/com/tf4/photospot/post/application/response/PostAllResponse.java
- src/main/java/com/tf4/photospot/post/application/response/PostDetail.java
- src/main/java/com/tf4/photospot/post/application/response/PostDetailResponse.java
- src/main/java/com/tf4/photospot/post/application/response/WriterResponse.java
- src/main/java/com/tf4/photospot/post/infrastructure/PostQueryRepository.java
- src/main/resources/static/docs/index.html
- src/test/java/com/tf4/photospot/post/application/PostServiceTest.java
- src/test/java/com/tf4/photospot/spring/docs/album/AlbumControllerDocsTest.java
- src/test/java/com/tf4/photospot/spring/docs/post/PostControllerDocsTest.java
<br>
- 방명록 작성자 여부 추가
- 스팟 주소 추가
<br>
- 동훈님이 슬랙으로 말씀하신 부분 수정했습니다!
<br>
> [Refactor] 방명록 상세 조회

- src/docs/asciidoc/api/post/post.adoc
- src/docs/asciidoc/api/user/user.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/com/tf4/photospot/auth/application/AuthService.java
- src/main/java/com/tf4/photospot/global/exception/domain/S3UploaderErrorCode.java
- src/main/java/com/tf4/photospot/global/exception/domain/UserErrorCode.java
- src/main/java/com/tf4/photospot/photo/application/S3Uploader.java
- src/main/java/com/tf4/photospot/photo/util/FileUtils.java
- src/main/java/com/tf4/photospot/post/application/PostService.java
- src/main/java/com/tf4/photospot/post/infrastructure/PostQueryRepository.java
- src/main/java/com/tf4/photospot/post/presentation/PostController.java
- src/main/java/com/tf4/photospot/post/presentation/request/PostReportRequest.java
- src/main/java/com/tf4/photospot/user/application/UserService.java
- src/main/java/com/tf4/photospot/user/application/response/NicknameUpdateResponse.java
- src/main/java/com/tf4/photospot/user/application/response/ProfileUpdateResponse.java
- src/main/java/com/tf4/photospot/user/application/response/UserInfoResponse.java
- src/main/java/com/tf4/photospot/user/domain/User.java
- src/main/java/com/tf4/photospot/user/presentation/UserController.java
- src/main/java/com/tf4/photospot/user/presentation/request/NicknameUpdateRequest.java
- src/main/resources/static/docs/index.html
- src/test/java/com/tf4/photospot/bookmark/presentation/request/AddBookmarkHttpRequestTest.java
- src/test/java/com/tf4/photospot/photo/util/FileUtilsTest.java
- src/test/java/com/tf4/photospot/post/application/PostServiceTest.java
- src/test/java/com/tf4/photospot/post/presentation/request/PostReportRequestTest.java
- src/test/java/com/tf4/photospot/spot/presentation/SpotControllerTest.java
- src/test/java/com/tf4/photospot/spring/docs/post/PostControllerDocsTest.java
- src/test/java/com/tf4/photospot/spring/docs/user/UserControllerDocsTest.java
- src/test/java/com/tf4/photospot/support/TestFixture.java
- src/test/java/com/tf4/photospot/user/application/UserServiceTest.java
<br>
- 신고 사유 200자 제한 추가
- 신고 목록 조회 기능 삭제
- 이미지 업로드 시 파일 이름에서 확장자명 추출하여 content type 설정
- 프로필 변경 요청 multipart에서 request 필드 삭제
- 닉네임 변경 api 추가
- 사용자 정보 조회 api 추가
> [Feat] 신고, 사진 업로드 리팩토링 및 사용자 기능 추가

- src/main/java/com/tf4/photospot/auth/application/KakaoService.java
> feat: kakao prefix 띄어쓰기 추가

- src/docs/asciidoc/api/user/user.adoc
- src/main/java/com/tf4/photospot/global/exception/domain/PostErrorCode.java
- src/main/java/com/tf4/photospot/global/exception/domain/UserErrorCode.java
- src/main/java/com/tf4/photospot/post/application/PostService.java
- src/main/java/com/tf4/photospot/post/domain/Post.java
- src/main/java/com/tf4/photospot/post/domain/PostReport.java
- src/main/java/com/tf4/photospot/post/domain/PostReportRepository.java
- src/main/java/com/tf4/photospot/post/infrastructure/PostQueryRepository.java
- src/main/java/com/tf4/photospot/user/application/UserService.java
- src/main/java/com/tf4/photospot/user/domain/User.java
- src/main/java/com/tf4/photospot/user/domain/UserReport.java
- src/main/java/com/tf4/photospot/user/domain/UserReportRepository.java
- src/main/java/com/tf4/photospot/user/infrastructure/UserQueryRepository.java
- src/main/java/com/tf4/photospot/user/presentation/UserController.java
- src/main/resources/static/docs/index.html
- src/test/java/com/tf4/photospot/auth/application/AuthServiceTest.java
- src/test/java/com/tf4/photospot/post/application/PostServiceTest.java
- src/test/java/com/tf4/photospot/post/domain/PostTest.java
- src/test/java/com/tf4/photospot/spring/docs/user/UserControllerDocsTest.java
- src/test/java/com/tf4/photospot/user/application/UserServiceTest.java
<br>
- 유저 신고 API 추가
<br>
- 신고 시 테이블에만 추가되고 신고한 사용자의 게시글에 대한 로직은 적용하지 않았습니다.
- 아까 회의 때 말씀하셨던 내용이 이게 맞는지 확인해주세요~ 
<br>
> [Feat] 유저 신고 API 추가

- src/main/java/com/tf4/photospot/auth/application/AppleService.java
- src/main/java/com/tf4/photospot/auth/application/AuthService.java
- src/main/java/com/tf4/photospot/auth/application/request/AppleRefreshTokenRequest.java
- src/main/java/com/tf4/photospot/auth/application/request/AppleRevokeRequest.java
- src/main/java/com/tf4/photospot/auth/infrastructure/AppleClient.java
- src/main/java/com/tf4/photospot/auth/util/KeyParser.java
- src/main/java/com/tf4/photospot/global/config/security/SecurityConfig.java
- src/main/java/com/tf4/photospot/global/exception/ApiException.java
- src/main/java/com/tf4/photospot/global/exception/GlobalExceptionHandler.java
- src/main/java/com/tf4/photospot/global/exception/domain/AuthErrorCode.java
- src/main/java/com/tf4/photospot/global/exception/domain/DetailApiException.java
- src/main/java/com/tf4/photospot/global/filter/ReqResLoggingFilter.java
- src/main/resources/static/docs/index.html
- src/test/java/com/tf4/photospot/auth/application/AuthServiceTest.java
- 애플 회원탈퇴 로직 수정
- 외부 서버와 통신하는 경우 DetailApiException 객체를 이용해 에러 스택 logging
<br>
> [Refactor] 애플 회원탈퇴 로직 수정

- src/main/resources/logback-spring.xml
> [Refactor] logback 파일 수정

- src/docs/asciidoc/api/common/common.adoc
- src/main/java/com/tf4/photospot/post/application/PostService.java
- src/main/java/com/tf4/photospot/post/application/response/TagResponse.java
- src/main/java/com/tf4/photospot/post/domain/Tag.java
- src/main/java/com/tf4/photospot/post/domain/TagType.java
- src/main/java/com/tf4/photospot/post/presentation/PostController.java
- src/main/java/com/tf4/photospot/post/presentation/response/TagListResponse.java
- src/main/resources/application.yml
- src/main/resources/static/docs/index.html
- src/test/java/com/tf4/photospot/post/application/PostServiceTest.java
- src/test/java/com/tf4/photospot/post/presentation/response/TagListResponseTest.java
- src/test/java/com/tf4/photospot/spring/docs/album/AlbumControllerDocsTest.java
- src/test/java/com/tf4/photospot/spring/docs/common/CommonController.java
- src/test/java/com/tf4/photospot/spring/docs/common/CommonDocsTest.java
- src/test/java/com/tf4/photospot/spring/docs/post/PostControllerDocsTest.java
- src/test/java/com/tf4/photospot/support/TestFixture.java
<br>
- 태그 목록 조회시 타입 별로 반환
- 태그에 타입 칼럼 추가
<br>
- 태그 목록을 타입(긍정, 부정, 기타)별로 구분할 수 있도록 수정했습니다.
<br>
> [Refactor] 태그 수정

- src/main/java/com/tf4/photospot/post/domain/Tag.java
<br>
- tag type이 ddl auto validation에서 문제가 생겨서 수정했습니다.
<br>
<br>
> [fix] tag type ddl-auto validation 추가

- src/main/java/com/tf4/photospot/global/exception/GlobalExceptionHandler.java
<br>
- 500 예외 에러 로그 추가
<br>
- unexpected 예외에 에러 로그를 추가했습니다
<br>
> [chore] 500 예외 에러 로그 추가

- src/main/java/com/tf4/photospot/global/config/MultipartJackson2HttpMessageConverter.java
- src/main/java/com/tf4/photospot/global/exception/GlobalExceptionHandler.java
<br>
- 예외 cause null 체크
<br>
-
<br>
> fix: requestpart로 json 오는 경우 octet stream convert 추가

- .github/workflows/ci_cd_prod.yml
- Dockerfile
- appspec-prod.yml
- src/main/resources/application.yml
<br>
- 운영 서버 CI/CD 추가
<br>
- 
<br>
> [Chore] 운영 서버 CI/CD

- .github/workflows/ci-cd.yml
- .github/workflows/ci_cd_prod.yml
- Dockerfile
<br>
- 도커파일 프로필 주입 오류 수정
<br>
-
<br>
> [chore] 도커파일 수정

- .github/workflows/ci_cd_prod.yml
- build.gradle
- src/main/java/com/tf4/photospot/global/config/security/SecurityConfig.java
<br>
- actuator 추가
- docker tag 수정
<br>
-
<br>
> [Chore] actuator 추가, docker image tag 수정

- .github/workflows/ci_cd_prod.yml
- build.gradle
- src/main/java/com/tf4/photospot/global/config/security/SecurityConfig.java
<br>
- docker tag 수정
<br>
-
<br>
> [Chore] docker tag 수정

- .github/workflows/ci_cd_prod.yml
> chore: cicd zip 수정

- .github/workflows/ci_cd_prod.yml
> chore: codedeploy stop 수정

- src/docs/asciidoc/api/post/post.adoc
- src/main/java/com/tf4/photospot/global/exception/domain/PostErrorCode.java
- src/main/java/com/tf4/photospot/post/application/PostService.java
- src/main/java/com/tf4/photospot/post/infrastructure/PostQueryRepository.java
- src/main/java/com/tf4/photospot/post/presentation/PostController.java
- src/main/java/com/tf4/photospot/post/presentation/request/PostsDeleteHttpRequest.java
- src/main/java/com/tf4/photospot/spot/infrastructure/SpotJdbcRepository.java
- src/main/resources/static/docs/index.html
- src/test/java/com/tf4/photospot/post/application/PostServiceTest.java
- src/test/java/com/tf4/photospot/spring/docs/album/AlbumControllerDocsTest.java
- src/test/java/com/tf4/photospot/spring/docs/post/PostControllerDocsTest.java
- src/test/java/com/tf4/photospot/support/TestFixture.java
> [Feat] posts delete

- src/main/java/com/tf4/photospot/photo/domain/Bubble.java
<br>
- posX, posY 인식 못해서 colunm 애노테이션 추가
<br>
-
<br>
> fix: posX, posY 인식 못해서 colunm 애노테이션 추가

- src/docs/asciidoc/api/album/album.adoc
- src/main/java/com/tf4/photospot/album/application/AlbumService.java
- src/main/java/com/tf4/photospot/album/domain/Album.java
- src/main/java/com/tf4/photospot/album/domain/AlbumUser.java
- src/main/java/com/tf4/photospot/album/infrastructure/AlbumQueryRepository.java
- src/main/java/com/tf4/photospot/album/presentation/AlbumController.java
- src/main/java/com/tf4/photospot/album/presentation/request/RenameAlbumHttpRequest.java
- src/test/java/com/tf4/photospot/album/application/AlbumServiceTest.java
- src/test/java/com/tf4/photospot/album/domain/AlbumTest.java
- src/test/java/com/tf4/photospot/spring/docs/album/AlbumControllerDocsTest.java
<br>
- 앨범 이름 변경 기능 추가
<br>
-
<br>
> feat: 앨범 이름 변경

- src/main/java/com/tf4/photospot/user/application/UserService.java
- src/main/java/com/tf4/photospot/user/domain/User.java
- src/main/java/com/tf4/photospot/user/domain/UserReport.java
- src/main/java/com/tf4/photospot/user/presentation/UserController.java
- src/main/java/com/tf4/photospot/user/presentation/request/UserReportRequest.java
- src/test/java/com/tf4/photospot/spring/docs/user/UserControllerDocsTest.java
- src/test/java/com/tf4/photospot/user/application/UserServiceTest.java
<br>
- 유저 신고 시 사유 항목 추가
<br>
-
<br>
> refactor: 유저 신고 시 사유 항목 추가

- src/main/java/com/tf4/photospot/bookmark/application/BookmarkService.java
- src/main/java/com/tf4/photospot/bookmark/application/response/BookmarkOfSpotResponse.java
- src/main/java/com/tf4/photospot/bookmark/infrastructure/BookmarkQueryRepository.java
- src/main/java/com/tf4/photospot/spot/application/SpotService.java
- src/main/java/com/tf4/photospot/spot/application/response/SpotResponse.java
- src/main/java/com/tf4/photospot/spot/presentation/SpotController.java
- src/main/java/com/tf4/photospot/spot/presentation/response/SpotHttpResponse.java
- src/test/java/com/tf4/photospot/bookmark/application/BookmarkServiceTest.java
- src/test/java/com/tf4/photospot/spot/application/SpotServiceTest.java
- src/test/java/com/tf4/photospot/spot/presentation/SpotControllerTest.java
- src/test/java/com/tf4/photospot/spring/docs/spot/SpotControllerDocsTest.java
<br>
- 스팟 조회 시 유저의 북마크 정보 추가
<br>
-
<br>
> refactor: 스팟 조회 시 유저의 북마크 정보 추가

- src/main/java/com/tf4/photospot/bookmark/application/BookmarkService.java
- src/main/java/com/tf4/photospot/bookmark/domain/BookmarkFolder.java
- src/main/java/com/tf4/photospot/bookmark/presentation/BookmarkController.java
- src/main/java/com/tf4/photospot/bookmark/presentation/request/UpdateBookmarkFolderHttpRequest.java
- src/test/java/com/tf4/photospot/bookmark/application/BookmarkServiceTest.java
- src/test/java/com/tf4/photospot/spring/docs/bookmark/BookmarkControllerDocsTest.java
<br>
- update bookmark folder 기능
<br>
-
<br>
> feat: update bookmark folder 기능
